### ISSUE TITLE
Some errors when putting event files produced by exptools2 through BIDS validator (BIDS 1.2.0)

### ISSUE THREAD

**Issue by marcoaqil** [VU-Cog-Sci/exptools2#14]
As from title. I note that these files were produced when i did the pilot so this might have already been addressed in a more recent exptools2 version. Delete issue if that is the case! 

Error 1: [Code 20] EVENTS_COLUMN_ONSET
First column of the events file must be named 'onset'

Error 2: [Code 21] EVENTS_COLUMN_DURATION
Second column of the events file must be named 'duration'

Error 3: [Code 22] TSV_EQUAL_ROWS
All rows must have the same number of columns as there are headers.

Error 4: [Code 23] TSV_EMPTY_CELL
Empty cell in TSV file detected: The proper way of labeling missing values is "n/a".

Warning 1: [Code 82] CUSTOM_COLUMN_WITHOUT_DESCRIPTION
Tabular file contains custom columns not described in a data dictionary

**Comment by lukassnoek** [comment]
The logfiles from exptools2 are not meant to be directly BIDS-compatible (at least, that was not my intention at the time). It's created in such a way that it's easily manipulated/filtered/etc and as such can be easily made BIDS-compatible. The first two errors can be easily fixed, which would make for a relatively easy PR. I'm not so sure about the third and fourth errors. This would make manipulating/filtering these files less straightforward, I think (w.r.t. error 4: leaving missing values empty allows you to filter them out easily with pandas, e.g., using `df.dropna(how='any', axis=0)`; not as straightforward when missing values are coded as `"n/a"`). 

What do you think, @tknapen ?

**Comment by marcoaqil** [comment]
gotcha! i (mistakenly) understood from @tknapen that the logfiles should be directly BIDS-compatible. whatever you guys prefer.
